### PR TITLE
Fix calculate_macs() for Linear layers.

### LINKED ISSUE #77: Error in computing Linear Layer Multiply adds
**Describe the bug**
When the linear layer has a multidimensional input and output (shape with 3 dimensions or more) the computed multiple adds will be incorrect.  

**To Reproduce**

Add line similar to  in model with 
```
model_stats = summary(model, input_size, img_metas=img_metas, gt_semantic_seg=seg, depth=9, col_names=["input_size", "kernel_size", "output_size", "num_params", "mult_adds"])
```

Make sure the linear layer has multiple dimensions as below.
```
Layer (type:depth-idx)            Input Shape               Kernel Shape              Output Shape              Param #         Mult-Adds
           Linear: 5-8             [1, 22528, 64]            [64, 256]                 [1, 22528, 256]           16,640                    16,640
```

**Expected behavior**

Notice the number of multiply adds is listed as 16640 but should be 374865920

It appears line 161 of https://github.com/TylerYep/torchinfo/blob/main/torchinfo/layer_info.py fails to take into account that the behavior of linear will require applying the kernel beyond the single output dimension.

**Screenshots**

```
Layer (type:depth-idx)            Input Shape               Kernel Shape              Output Shape              Param #         Mult-Adds
           Linear: 5-8             [1, 22528, 64]            [64, 256]                 [1, 22528, 256]           16,640                    16,640
```

**Additional context**
Just noticed this was not the correct number of FLOPS in a model using a linear layer such as this.

### PR DESCRIPTION
**Pull request by andravin**
Fixes #77.

### CODE REVIEW

**Comment by TylerYep** [comment]
Could you add a unit test and also explain why this fixes the issue?

**Comment by andravin** [comment]
The  [documentation](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) for `torch.nn.Linear` says the input tensor can have "any number of dimensions."

Currently, torchinfo only handles two-dimensional input tensors correctly, any additional dimensions are ignored:
```python
                    self.macs += self.output_size[0] * cur_params
```

The change accounts for all of the leading dimensions:
```python
                elif "Linear" in self.class_name:
                    self.macs += int(cur_params * prod(self.output_size[:-1]))
```

You can think of `torch.nn.Linear` as a tensor-matrix multiplication or n-mode product, with the last dimension of the tensor as the "mode." This is equivalent to matrix multiplication if we first unfold all of the leading dimensions of the tensor into a single dimension. The size of the unfolded dimension is `prod(self.output_size[:-1])`.

See section A.2.3 N-mode Product in this [reference](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9780470590676.app1) for a detailed explanation.

**Comment by andravin** [comment]
The way `LayerInfo.calculate_macs` just checks a partial match on the class-name for `Conv` and now `Linear` and ignores the module name seems dicey. Exact matches against fully qualified `<module>.<class>` names would seem more robust. 

Also, any unrecognized layer is assumed to be a Linear layer with 2D input, judging by the code in the `else` block. That also seems error-prone. It might be better to throw an exception for unsupported layers.

**Comment by andravin** [comment]
I added a unit test for torch.nn.Linear that uses a 3D input tensor.

**Comment by TylerYep** [comment]
Thanks for the explanation. It seems very reasonable that this error would cause other model outputs to change, so feel free to update those as suggested by the test errors.

I think this specific calculation has a lot of room for improvement, since it was only hardcoded with a few layer types to begin with. It would be great to enhance the `<module>.<class>` exact match code as well, but feel free to tackle these things in a separate PR.

**Comment by andravin** [comment]
It looks like [torch.nn.Embedding](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html) layers have the same bug that `torch.nn.Linear` layers did.

**Comment by andravin** [comment]
@TylerYep, I followed your guidance and changed the ground truth in `flant_t5_small.out` to equal the output of the unit tests with the linear layer MACs fix.

Let me know if you prefer the three commits in this pull request to be squashed into a single commit.

**Pull request merged**
