### PR TITLE
attempt to fix #117

### LINKED ISSUE #117: Error when using nn.UninitializedParameter
**Describe the bug**
A `ValueError` is raised when trying to use unavailable operation `nelement()` on an `UninitializedParameter`.

`summary` method goes over all the modules in the model and tries to get the number of parameters, but that's not possible with an `UninitializedParameter`.

**To Reproduce**
```python
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.param = nn.UninitializedParameter()
    
    def init_param(self):
        self.param = nn.Parameter(torch.zeros(1))
    
    def forward(self, x):
        self.init_param()
        return x

net = Net()
torchinfo.summary(net, input_size=(1, 1))
```

**Output**
First part of the stack trace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\miniconda3\envs\cudalab\lib\site-packages\torchinfo\torchinfo.py in forward_pass(model, x, batch_dim, cache_forward_pass, device, **kwargs)
    260             if isinstance(x, (list, tuple)):
--> 261                 _ = model.to(device)(*x, **kwargs)
    262             elif isinstance(x, dict):

~\miniconda3\envs\cudalab\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1108             for hook in (*_global_forward_pre_hooks.values(), *self._forward_pre_hooks.values()):
-> 1109                 result = hook(self, input)
   1110                 if result is not None:

~\miniconda3\envs\cudalab\lib\site-packages\torchinfo\torchinfo.py in pre_hook(***failed resolving arguments***)
    457         info = LayerInfo(var_name, module, curr_depth, idx[curr_depth], parent_info)
--> 458         info.calculate_num_params()
    459         info.check_recursive(summary_list)

~\miniconda3\envs\cudalab\lib\site-packages\torchinfo\layer_info.py in calculate_num_params(self)
    125         for name, param in self.module.named_parameters():
--> 126             self.num_params += param.nelement()
    127             if param.requires_grad:

~\miniconda3\envs\cudalab\lib\site-packages\torch\nn\parameter.py in __torch_function__(cls, func, types, args, kwargs)
    120             return super().__torch_function__(func, types, args, kwargs)
--> 121         raise ValueError(
    122             'Attempted to use an uninitialized parameter in {}. '

ValueError: Attempted to use an uninitialized parameter in <method 'numel' of 'torch._C._TensorBase' objects>. This error happens when you are using a `LazyModule` or explicitly manipulating `torch.nn.parameter.UninitializedParameter` objects. When using LazyModules Call `forward` with a dummy batch to initialize the parameters before calling torch functions
```

**Expected behavior**
To check if a `Module` is an instance of an `UninitializedParameter` and skip calls to unavailable operations.

It would still be nice to show somehow in the printed summary table (maybe 'uninitialized'?).

**Context:**
 - OS: Windows 10
 - Python 3.9.7
 - pytorch 1.10.1 (py3.9_cpu_0)
 - torchinfo 1.6.0

### PR DESCRIPTION
**Pull request by jedi2610**

### CODE REVIEW

**Comment by jedi2610** [comment]
@TylerYep i had to use the `is_lazy` function from [torch.nn.parameter](https://pytorch.org/docs/stable/_modules/torch/nn/parameter.html#UninitializedParameter) cause doing something like

```python
from torch.nn import parameter
LAZY_MODULES = (parameter.UninitializedTensorMixin,)

...

if isinstance(param, LAZY_MODULES):
    continue
```

would cause the following error in `mypy` (something like [this](https://stackoverflow.com/questions/39382937/mypy-spurious-error-module-has-no-attribute-xpath-with-etree))
```
torchinfo/layer_info.py:15: error: Module has no attribute "UninitializedTensorMixin"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

which would cause the tests to fail.

want me to make any more changes? or move the check to somewhere else?

**Comment by jedi2610** [comment]
just googled more and found that we can bypass the error by directly importing `UninitializedTensorMixin` from `torch.nn.parameter`.

something like:
```python
from torch.nn.parameter import UninitializedTensorMixin
```

so if you want i can prolly do the thing i mentioned above, so we get more control over the check. but using the `is_lazy` function can be advantageous too. for example if they decided to add more Lazymodules then it wouldn't break for the newly add modules (assuming that they don't inherit from `UninitializedTensorMixin`). i'm confused so you tell which one i should go with.

**Comment by TylerYep** [comment]
It's hard to review this without any test cases to see if it works or not. Can we add those first?

**Comment by jedi2610** [comment]
nvm, i'll open a new PR as it's hard to see the commits too

**Pull request closed without merging**
