### PR TITLE
accepting dict input data

### PR DESCRIPTION
**Pull request by e-dorigatti**
Hi, this PR is meant to allow dicts as input to the summary function, which are then used as kwargs for the model.
I disabled `too-many-branches` from pylint to avoid major restructuring, what is the best way to proceed here in your opinion?

### CODE REVIEW

**Comment by TylerYep** [comment]
Hey, thanks for starting work on this! It looks good so far, could you also add an output test for this change?

You also need to fix a DeepSource build issue linked above. (but ignore the 5 delete errors, those are false positives)

As a side note, this change will only allow dictionaries to be passed in the topmost layer of the network. To completely support dictionaries as inputs, you also need to modify layer_info.py (there is a TODO on line 69) and figure out a nice way of displaying the sizes of a layer with dicts. Feel free to tackle this as well if you want :)

**Comment by e-dorigatti** [comment]
Hi, I made the test and fixed the issue.

> As a side note, this change will only allow dictionaries to be passed in the topmost layer of the network. To completely support dictionaries as inputs, you also need to modify layer_info.py (there is a TODO on line 69) and figure out a nice way of displaying the sizes of a layer with dicts.

Sorry but I am not sure what you mean here. The dictionary is used as keyword arguments for the model, so the model gets tensors as usual. Or are you thinking at handling nested dictionaries?

**Comment by TylerYep** [comment]
For example, if you have a model like this, the output sizes do not show up properly.
```python
class DictLayer:
    def forward(x1, y1):
        ...
        return {"x1": x2, "y1": y2}

class MyModel:
    def __init__(self):
        self.layer1 = DictLayer()
        self.layer2 = DictLayer()
    def forward(x1, y1):
        z = self.layer1(**z)
        z = self.layer1(**z)
        return z
```

**Comment by TylerYep** [comment]
Overall, the changes look good. Thanks for contributing! If you have thoughts on how to fix the above issue, feel free to let me know.

I'll probably create a new release with this change in the next week or so.

**Pull request merged**
