### PR TITLE
update support to torchvison mask/faster rcnn model summary

### PR DESCRIPTION
**Pull request by michiroooo**
update support to torchvison mask/faster rcnn model summary
- update layer_info to support OrderedDict and ImageList case where used within torchvison/detection
- unittest passed

### CODE REVIEW

**Comment by TylerYep** [comment]
Thanks! Can you add the test case too? (try to use a small input)

**Comment by michiroooo** [comment]
@TylerYep Test case added - I've used faster-cnn model, this would be smaller model size than mask-rcnn which is also generalized-rcnn variant would cover same use-case.

**Comment by TylerYep** [comment]
Awesome, thanks for the contribution!

**Comment by TylerYep** [comment]
What does to_image_list return? I suspect it is returning a custom object instead of a true Python list.

Try passing the input size to the model instead.

**Comment by hongsoog** [comment]
@TylerYep 
Thanks for your reading and reply.

The return type from ```to_image_list``` is as follows:
```python
type(image_list): <class 'maskrcnn_benchmark.structures.image_list.ImageList'>
```
with following code:
```
 def compute_prediction(self, image):
        image = self.transforms(image)  # convert PIL Image to torch Tensor
        image_list = to_image_list(image, self.cfg.DATALOADER.SIZE_DIVISIBILITY).to(self.device)

        print(f"type(image_list): {type(image_list)}")
        
         torchinfo.summary(model=self.model,
                          input_data = image_list,
                          col_names = ("input_size", "output_size", "num_params", "kernel_size", "mult_adds"),
                          verbose=2)
       
        # temporary comment out for testing torchinfo.summary
        # with torch.no_grad():
        #    pred = self.model(image_list)
        #    pred = pred[0].to(self.cpu_device)
        #return pred
```
You can checkout the ```ImageList``` class definition at [here](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/structures/image_list.py).

Also, I have tried with ```input_size``` instead of ```input_data``` as follows:
```python
 def compute_prediction(self, image):
        image = self.transforms(image)  # convert PIL Image to torch Tensor
        image_list = to_image_list(image, self.cfg.DATALOADER.SIZE_DIVISIBILITY).to(self.device)

        print(f"type(image_list): {type(image_list)}")
        
         torchinfo.summary(model=self.model,
                          input_size=(1, 3, 480, 576),
                          #input_data = image_list,
                          col_names = ("input_size", "output_size", "num_params", "kernel_size", "mult_adds"),
                          verbose=2)
       
        # temporary comment out for testing torchinfo.summary
        # with torch.no_grad():
        #    pred = self.model(image_list)
        #    pred = pred[0].to(self.cpu_device)
        #return pred
```
The error message resuling from above code modification as follows:
```python
...
Traceback (most recent call last):
  File "./detect_model_onnx.py", line 220, in <module>
    prediction = demo.run_on_pil_image(pil_image)
  File "./detect_model_onnx.py", line 60, in run_on_pil_image
    prediction = self.compute_prediction(pil_image)
  File "./detect_model_onnx.py", line 83, in compute_prediction
    verbose=2)
  File "/home/kimkk/miniconda3/envs/lomin/lib/python3.6/site-packages/torchinfo/torchinfo.py", line 124, in summary
    validate_user_params(input_data, col_names, verbose)
  File "/home/kimkk/miniconda3/envs/lomin/lib/python3.6/site-packages/torchinfo/torchinfo.py", line 173, in validate_user_params
    raise ValueError(f"You must pass input_data in order to use column {col}")
ValueError: You must pass input_data in order to use column input_size
```
It says that ```You must pass input_data in order to use column input_size```. 
If I omit ```col_name``` parameter, when calling ```torchinfo.summary()```, there's no error but the output contains only ```Param # ``` column as follows:

```python
================================================================================
Layer (type:depth-idx)                                  Param #
================================================================================
├─Sequential: 1-1                                       --
|    └─body.stem.conv1.weight
|    └─body.layer1.0.downsample.0.weight
|    └─body.layer1.0.conv1.weight
|    └─body.layer1.0.conv2.weight
|    └─body.layer1.0.conv3.weight
|    └─body.layer1.1.conv1.weight
|    └─body.layer1.1.conv2.weight
|    └─body.layer1.1.conv3.weight
|    └─body.layer1.2.conv1.weight
|    └─body.layer1.2.conv2.weight
|    └─body.layer1.2.conv3.weight
|    └─body.layer2.0.downsample.0.weight
|    └─body.layer2.0.conv1.weight
|    └─body.layer2.0.conv2.weight
|    └─body.layer2.0.conv3.weight
|    └─body.layer2.1.conv1.weight
|    └─body.layer2.1.conv2.weight
|    └─body.layer2.1.conv3.weight
|    └─body.layer2.2.conv1.weight
|    └─body.layer2.2.conv2.weight
|    └─body.layer2.2.conv3.weight
|    └─body.layer2.3.conv1.weight
|    └─body.layer2.3.conv2.weight
|    └─body.layer2.3.conv3.weight
|    └─body.layer3.0.downsample.0.weight
|    └─body.layer3.0.conv1.weight
|    └─body.layer3.0.conv2.weight
|    └─body.layer3.0.conv3.weight
|    └─body.layer3.1.conv1.weight
|    └─body.layer3.1.conv2.weight
|    └─body.layer3.1.conv3.weight
|    └─body.layer3.2.conv1.weight
|    └─body.layer3.2.conv2.weight
|    └─body.layer3.2.conv3.weight
|    └─body.layer3.3.conv1.weight
|    └─body.layer3.3.conv2.weight
|    └─body.layer3.3.conv3.weight
|    └─body.layer3.4.conv1.weight
|    └─body.layer3.4.conv2.weight
|    └─body.layer3.4.conv3.weight
|    └─body.layer3.5.conv1.weight
|    └─body.layer3.5.conv2.weight
|    └─body.layer3.5.conv3.weight
|    └─body.layer4.0.downsample.0.weight
|    └─body.layer4.0.conv1.weight
|    └─body.layer4.0.conv2.weight
|    └─body.layer4.0.conv3.weight
|    └─body.layer4.1.conv1.weight
|    └─body.layer4.1.conv2.weight
|    └─body.layer4.1.conv3.weight
|    └─body.layer4.2.conv1.weight
|    └─body.layer4.2.conv2.weight
|    └─body.layer4.2.conv3.weight
|    └─fpn.fpn_inner2.weight
|    └─fpn.fpn_layer2.weight
|    └─fpn.fpn_inner3.weight
|    └─fpn.fpn_layer3.weight
|    └─fpn.fpn_inner4.weight
|    └─fpn.fpn_layer4.weight
|    └─fpn.top_blocks.p6.weight
|    └─fpn.top_blocks.p7.weight
|    └─ResNet: 2-1                                      --
|    |    └─stem.conv1.weight
|    |    └─layer1.0.downsample.0.weight
|    |    └─layer1.0.conv1.weight
|    |    └─layer1.0.conv2.weight
|    |    └─layer1.0.conv3.weight
|    |    └─layer1.1.conv1.weight
|    |    └─layer1.1.conv2.weight
|    |    └─layer1.1.conv3.weight
|    |    └─layer1.2.conv1.weight
|    |    └─layer1.2.conv2.weight
|    |    └─layer1.2.conv3.weight
|    |    └─layer2.0.downsample.0.weight
|    |    └─layer2.0.conv1.weight
|    |    └─layer2.0.conv2.weight
|    |    └─layer2.0.conv3.weight
|    |    └─layer2.1.conv1.weight
|    |    └─layer2.1.conv2.weight
|    |    └─layer2.1.conv3.weight
|    |    └─layer2.2.conv1.weight
|    |    └─layer2.2.conv2.weight
|    |    └─layer2.2.conv3.weight
|    |    └─layer2.3.conv1.weight
|    |    └─layer2.3.conv2.weight
|    |    └─layer2.3.conv3.weight
|    |    └─layer3.0.downsample.0.weight
|    |    └─layer3.0.conv1.weight
|    |    └─layer3.0.conv2.weight
|    |    └─layer3.0.conv3.weight
|    |    └─layer3.1.conv1.weight
|    |    └─layer3.1.conv2.weight
|    |    └─layer3.1.conv3.weight
|    |    └─layer3.2.conv1.weight
|    |    └─layer3.2.conv2.weight
|    |    └─layer3.2.conv3.weight
|    |    └─layer3.3.conv1.weight
|    |    └─layer3.3.conv2.weight
|    |    └─layer3.3.conv3.weight
|    |    └─layer3.4.conv1.weight
|    |    └─layer3.4.conv2.weight
|    |    └─layer3.4.conv3.weight
|    |    └─layer3.5.conv1.weight
|    |    └─layer3.5.conv2.weight
|    |    └─layer3.5.conv3.weight
|    |    └─layer4.0.downsample.0.weight
|    |    └─layer4.0.conv1.weight
|    |    └─layer4.0.conv2.weight
|    |    └─layer4.0.conv3.weight
|    |    └─layer4.1.conv1.weight
|    |    └─layer4.1.conv2.weight
|    |    └─layer4.1.conv3.weight
|    |    └─layer4.2.conv1.weight
|    |    └─layer4.2.conv2.weight
|    |    └─layer4.2.conv3.weight
|    |    └─StemWithFixedBatchNorm: 3-1                 (9,408)
|    |    |    └─conv1.weight
|    |    └─Sequential: 3-2                             (212,992)
|    |    |    └─0.downsample.0.weight
|    |    |    └─0.conv1.weight
|    |    |    └─0.conv2.weight
|    |    |    └─0.conv3.weight
|    |    |    └─1.conv1.weight
|    |    |    └─1.conv2.weight
|    |    |    └─1.conv3.weight
|    |    |    └─2.conv1.weight
|    |    |    └─2.conv2.weight
|    |    |    └─2.conv3.weight
|    |    └─Sequential: 3-3                             1,212,416
|    |    |    └─0.downsample.0.weight
|    |    |    └─0.conv1.weight
|    |    |    └─0.conv2.weight
|    |    |    └─0.conv3.weight
|    |    |    └─1.conv1.weight
|    |    |    └─1.conv2.weight
|    |    |    └─1.conv3.weight
|    |    |    └─2.conv1.weight
|    |    |    └─2.conv2.weight
|    |    |    └─2.conv3.weight
|    |    |    └─3.conv1.weight
|    |    |    └─3.conv2.weight
|    |    |    └─3.conv3.weight
|    |    └─Sequential: 3-4                             7,077,888
|    |    |    └─0.downsample.0.weight
|    |    |    └─0.conv1.weight
|    |    |    └─0.conv2.weight
|    |    |    └─0.conv3.weight
|    |    |    └─1.conv1.weight
|    |    |    └─1.conv2.weight
|    |    |    └─1.conv3.weight
|    |    |    └─2.conv1.weight
|    |    |    └─2.conv2.weight
|    |    |    └─2.conv3.weight
|    |    |    └─3.conv1.weight
|    |    |    └─3.conv2.weight
|    |    |    └─3.conv3.weight
|    |    |    └─4.conv1.weight
|    |    |    └─4.conv2.weight
|    |    |    └─4.conv3.weight
|    |    |    └─5.conv1.weight
|    |    |    └─5.conv2.weight
|    |    |    └─5.conv3.weight
|    |    └─Sequential: 3-5                             14,942,208
|    |    |    └─0.downsample.0.weight
|    |    |    └─0.conv1.weight
|    |    |    └─0.conv2.weight
|    |    |    └─0.conv3.weight
|    |    |    └─1.conv1.weight
|    |    |    └─1.conv2.weight
|    |    |    └─1.conv3.weight
|    |    |    └─2.conv1.weight
|    |    |    └─2.conv2.weight
|    |    |    └─2.conv3.weight
|    └─FPN: 2-2                                         --
|    |    └─fpn_inner2.weight
|    |    └─fpn_layer2.weight
|    |    └─fpn_inner3.weight
|    |    └─fpn_layer3.weight
|    |    └─fpn_inner4.weight
|    |    └─fpn_layer4.weight
|    |    └─top_blocks.p6.weight
|    |    └─top_blocks.p7.weight
|    |    └─Conv2d: 3-6                                 525,312
|    |    └─Conv2d: 3-7                                 9,438,208
|    |    └─Conv2d: 3-8                                 1,049,600
|    |    └─Conv2d: 3-9                                 9,438,208
|    |    └─Conv2d: 3-10                                2,098,176
|    |    └─Conv2d: 3-11                                9,438,208
|    |    └─LastLevelP6P7: 3-12                         28,313,600
|    |    |    └─p6.weight
|    |    |    └─p7.weight
├─RetinaNetModule: 1-2                                  --
|    └─head.cls_tower.0.weight
|    └─head.cls_tower.2.weight
|    └─head.cls_tower.4.weight
|    └─head.cls_tower.6.weight
|    └─head.bbox_tower.0.weight
|    └─head.bbox_tower.2.weight
|    └─head.bbox_tower.4.weight
|    └─head.bbox_tower.6.weight
|    └─head.cls_logits.weight
|    └─head.bbox_pred.weight
|    └─AnchorGenerator: 2-3                             --
|    |    └─BufferList: 3-13                            --
|    └─RetinaNetHead: 2-4                               --
|    |    └─cls_tower.0.weight
|    |    └─cls_tower.2.weight
|    |    └─cls_tower.4.weight
|    |    └─cls_tower.6.weight
|    |    └─bbox_tower.0.weight
|    |    └─bbox_tower.2.weight
|    |    └─bbox_tower.4.weight
|    |    └─bbox_tower.6.weight
|    |    └─cls_logits.weight
|    |    └─bbox_pred.weight
|    |    └─Sequential: 3-14                            37,752,832
|    |    |    └─0.weight
|    |    |    └─2.weight
|    |    |    └─4.weight
|    |    |    └─6.weight
|    |    └─Sequential: 3-15                            37,752,832
|    |    |    └─0.weight
|    |    |    └─2.weight
|    |    |    └─4.weight
|    |    |    └─6.weight
|    |    └─Conv2d: 3-16                                82,953
|    |    └─Conv2d: 3-17                                331,812
|    └─RetinaNetPostProcessor: 2-5                      --
================================================================================
Total params: 159,676,653
Trainable params: 159,454,253
Non-trainable params: 222,400
================================================================================
```
I want to get the information on "input_size", "output_size","kernel_size", "mult_adds" in addition to  "num_params".

Again, thanks for your reading.

Best regards

**Comment by TylerYep** [comment]
Hmm, ImageLists are currently not supported in torchinfo. Currently, `input_data` only accepts lists of tensors. Since ImageList is a custom object, torchinfo is unable to parse the object correctly. You can open a separate issue about this!

I'm not sure if I'll be able to create a special case for ImageLists yet, but I'll appreciate any PRs for this!

**Comment by hongsoog** [comment]
Dear TylerYep,
Thanks for your reading on long and somewhat speficific questions.

The ImageList is included in the https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark

Unfortunately, I'm a novice programmer who cannot handle this kind of issue. 
But in my understanding, this issue seems to be related to the PyTorch JIT interpreter.

After understaning PR concept and its procedure, I would open the PRs.

Either way, thanks for your kind reading of this issue.

Best Regard.

**Pull request merged**
