### PR TITLE
Uninitialized tensor fix

### PR DESCRIPTION
**Pull request by jedi2610**

### CODE REVIEW

**Comment by jedi2610** [comment]
@TylerYep there you go. again sorry for the mess, i'm not working from my PC so...

**Comment by TylerYep** [comment]
Curious why we need to skip these at all? Since torchinfo runs a forward pass over the model, perhaps we could get the number of elements at runtime / modify then once we get that info.

This PR looks good as a first pass to prevent torchinfo from crashing, but wondering if we can do better too.

I'll do a final review sometime next week.

**Comment by jedi2610** [comment]
i thought of that too, but then as we are only calculating params before the forward pass (`pre_hook`) i don't know how to do it. if we calculated the params during the forward pass (inside `hook`) maybe we can do it then. do you have any other ideas? maybe i'm missing something.

**Comment by TylerYep** [comment]
As a future improvement, we should be able to add code to the forward pass hook that adds parameters once the tensor is initialized, maybe in a separate variable, and then sum them when printing the summary.

**Comment by jedi2610** [comment]
i'm a little busy now, so i'll prolly open a new pr for that later next week.

**Comment by TylerYep** [comment]
Looks good to me, thanks for the fix! Looking forward to the next stage of improvements.

**Comment by jedi2610** [comment]
next week!

**Pull request merged**
